[package]
name = "consume-body"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
http-body-util = "0.1.2"
tokio = {version = "1.38.0", features = ['full']}
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
