[package]
name = "eg-starwars"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.5"
async-graphql-axum = "7.0.5"
axum = "0.7.5"
tokio = {version = "1.38.0", features = ['full']}
starwars = {path = "../../models/starwars"}